### ISSUE TITLE
'Remixing' tutorials

### ISSUE THREAD

**Issue by imdevarsh** [MystPi/scratch-tutorials#15]
You should be able to remix a Scratch Tutorial and add some more things onto it! Like how Scratch has a remixing system.

**Comment by MystPi** [comment]
I think that would lead to a lot of similar/duplicate tutorials, possibly making it hard to find unique and useful tutorials.

**Comment by imdevarsh** [comment]
If this was implemented then there should be a restriction where people can't clone other people's work.

**Comment by MystPi** [comment]
I just don't think tutorial remixing would be a good idea (for the reasons I listed above), even if there was that restriction. Sorry for the inconvenience. 😅
