### ISSUE TITLE
Suggestion: Markdown Guide

### ISSUE THREAD

**Issue by Adzboy** [MystPi/scratch-tutorials#3]
Add a guide to Markdown?

**Comment by MystPi** [comment]
Finished: https://scratchtutorials.vercel.app/markdown-guide. 😸

**Comment by Adzboy** [comment]
Cool

**Comment by imdevarsh** [comment]
@MystPi you should change the wording of the part where there is code, because I assume most people on Scratch Tutorials may not know, so something like 'text-based coding languages outside of Scratch'

**Comment by MystPi** [comment]
What do you mean? Could you open a PR with your suggested changes?
